[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "npx playwright install --with-deps"
]

[phases.build]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm --filter @arbi/api start"

[variables]
NODE_ENV = "production"
